### ISSUE TITLE
テキスト表示のアニメーション調査

### ISSUE THREAD

**Issue by epc1126** [illionillion/school-festival-2023#10]
テキスト表示の時のCSSのアニメーションを調査する。

**Comment by epc1126** [comment]
参考サイト
https://reffect.co.jp/react/framer-motion/
https://qiita.com/FumioNonaka/items/ccadd4261522aafe51f5

**Comment by illionillion** [comment]
> 参考サイト https://reffect.co.jp/react/framer-motion/ https://qiita.com/FumioNonaka/items/ccadd4261522aafe51f5

framer-motionいいね！！
React勉強ついでにやってみるのもアリかも〜

**Comment by epc1126** [comment]
https://github.com/illionillion/school-festival-2023/assets/148218092/9c75625f-9b08-4fd4-8fb4-509cc9a7a4ad

なんか落ちてくる感じにはできた！
キーワードクリックしたら回転とかも追加してみようかな～と思ったけどやり方わからなくて諦めた😂

**Comment by illionillion** [comment]
> test.mp4 
> なんか落ちてくる感じにはできた！ キーワードクリックしたら回転とかも追加してみようかな～と思ったけどやり方わからなくて諦めた😂

最初のキーワードのアニメーションはいいね！！
メモの方のアニメーションはばらついてる気がするからもうちょっと調整加えるか、別のアニメーション考えた方がいいかも〜

**Comment by epc1126** [comment]
https://github.com/illionillion/school-festival-2023/assets/148218092/c25de2d7-defc-41cf-9d86-971cca1867a6



> > test.mp4
> > なんか落ちてくる感じにはできた！ キーワードクリックしたら回転とかも追加してみようかな～と思ったけどやり方わからなくて諦めた😂
> 
> 最初のキーワードのアニメーションはいいね！！ メモの方のアニメーションはばらついてる気がするからもうちょっと調整加えるか、別のアニメーション考えた方がいいかも〜

ありがとうー！！
とりあえず揃えてみた！けど、別のアニメーションとかも色々試してみようと思うよ～

**Comment by illionillion** [comment]
> test2.mp4 
> > > test.mp4
> > > なんか落ちてくる感じにはできた！ キーワードクリックしたら回転とかも追加してみようかな～と思ったけどやり方わからなくて諦めた😂
> > 
> > 
> > 最初のキーワードのアニメーションはいいね！！ メモの方のアニメーションはばらついてる気がするからもうちょっと調整加えるか、別のアニメーション考えた方がいいかも〜
> 
> ありがとうー！！ とりあえず揃えてみた！けど、別のアニメーションとかも色々試してみようと思うよ～

うん！！
あとは紙吹雪のアニメーションとかも面白いかもね！！
https://coco-factory.jp/ugokuweb/move02/5-8/

これの場合はReactとTypeScriptで合うやつ探さなければだけど…。

**Comment by epc1126** [comment]
> うん！！ あとは紙吹雪のアニメーションとかも面白いかもね！！ https://coco-factory.jp/ugokuweb/move02/5-8/
> 
> これの場合はReactとTypeScriptで合うやつ探さなければだけど…。


https://github.com/illionillion/school-festival-2023/assets/148218092/395c87cd-624b-4e4d-9fa6-b4ee87fc8084

紙吹雪とか色々やってみたよー！イメージこんな感じで合ってる？
キーワード押したら回転も作れたけど謎機能すぎるかも

**Comment by illionillion** [comment]
> > うん！！ あとは紙吹雪のアニメーションとかも面白いかもね！！ https://coco-factory.jp/ugokuweb/move02/5-8/
> > これの場合はReactとTypeScriptで合うやつ探さなければだけど…。
> 
>  test3.mp4 
> 紙吹雪とか色々やってみたよー！イメージこんな感じで合ってる？ キーワード押したら回転も作れたけど謎機能すぎるかも

@epc1126 
いいね！最初のアニメーションはいいかも！！
採用しようかな！！

また新しいブランチ切ってプルリク飛ばしてほしい！！
