### ISSUE TITLE
長押し時の選択を無効化

### ISSUE THREAD

**Issue by illionillion** [illionillion/school-festival-2023#3]
長押し、選択した時に青いやつが出ないようにする
<img width="434" alt="image" src="https://github.com/illionillion/school-festival-2023/assets/60034520/a385ef20-a3a3-4403-bab3-253747cb34f3">

`user-select: none;`のCSSを該当部分に割り当てれば良い
https://cly7796.net/blog/css/disable-text-selection-in-css/

**Comment by illionillion** [comment]
@epc1126 締切来週まで、よろしくお願いしますー

**Comment by epc1126** [comment]
完了
